### ISSUE TITLE
shows error while export

### ISSUE THREAD

**Issue by pranavcp** [husseycoding/customordergrid#13]
hi there, i have installed this extension. while doing CSV export it shows the error. attached log file herewith. can you please check what is going wrong.
 
here is the screenshot of the log error file.
http://prntscr.com/f7qfk2
![1](https://cloud.githubusercontent.com/assets/6815249/26049697/8809bdec-3979-11e7-9a88-90ff905b24f2.png)

**Comment by husseycoding** [comment]
It looks like you could be joining two tables with the same alias name, can you confirm you are seeing this on a clean install of Magento with no other extensions installed?

**Comment by pranavcp** [comment]
hi there,
yes, it is clean installed.

**Comment by pranavcp** [comment]
also,  if this is just an issue of alias, can we change name of alias in our query?
can you let me know where can I change this?

**Comment by pranavcp** [comment]
also, if this is just an issue of alias, can we change name of alias in our query?
can you let me know where can I change this?

**Comment by lvekua** [comment]
I'm getting the same exact error when I export CSV is there a  fix for this?

**Comment by pranavcp** [comment]
I have removed this extension and added my custom code. must say, this extension is not proper tested.

**Comment by husseycoding** [comment]
We have just tested exporting from on a clean install with all available columns selected and there are no issues apparent.  If you have some more details available then please feel free to come back with a comment, but for now I'm closing the ticket.  @lvekua, if you believe your issue to be different and apparent on a clean install, please open a new ticket.
