### ISSUE TITLE
You cannot define a correlation name 'order' more than once

### ISSUE THREAD

**Issue by sachittandukar** [husseycoding/customordergrid#4]
Hi @husseycoding ,

I am getting this issue "You cannot define a correlation name 'order' more than once." whenever I try to export CSV. 

Can you please help me with this issue?

**Comment by husseycoding** [comment]
Is this with the latest version?  Can you tell me which columns you have selected so I can do some tests locally?

**Comment by sachittandukar** [comment]
I haven't select any columns. It's just normal export to CSV from order page.

This issue occurred on previous version and also after upgrading to latest version.

**Comment by husseycoding** [comment]
Sorry I meant which columns have you selected to be displayed on the order grid (so I can select the same locally and test an export).

**Comment by sachittandukar** [comment]
Sorry. I didn't get it at first.

Columns are on following order:
order no
purchased on
customer email
bill to name
ship to name
customer group
guest checkout
G.T. purchased
status

**Comment by husseycoding** [comment]
Ok thanks, I'll run some tests.

**Comment by sachittandukar** [comment]
Hi @husseycoding ,

Just want to know if this issue is specific to my site only. Were you able to re create issue?

**Comment by husseycoding** [comment]
Sorry, I haven't had time to look at this yet, but if in doubt feel free to test on a clean install with no other extensions - that should tell you if it's store specific.
