### ISSUE TITLE
Error while generating CSV for promotional code list (inside Shopping Cart Price Rules)

### ISSUE THREAD

**Issue by farazWebDev** [husseycoding/customordergrid#8]
I am getting this error: Fatal error: Call to a member function addData() on a non-object in /app/code/community/HusseyCoding/CustomOrderGrid/Model/Observer.php on line 49

while generating CSV for promotional code list
http://url/admin123/promo_quote/exportCouponsCsv/id/33/key/keynumber/

---if this extension is for only order page, then i think should not have a side effect on promotional code pages

**Comment by husseycoding** [comment]
Are you using the latest version of the extension and are you seeing this on a clean unmodified version of Magento and which version?

**Comment by farazWebDev** [comment]
Hi I am using this one: on My magento store CE 1.9.1.1
https://www.magentocommerce.com/magento-connect/custom-order-grid.html

**Comment by husseycoding** [comment]
Can you answer the questions above?

**Comment by farazWebDev** [comment]
Are you using the latest version of the extension    -----   **YES**

and are you seeing this on a clean unmodified version of Magento and which version?     ---- Obviously no one use on clean unmodified version, while working on project people need something, they search for shortest path, they find one extension, they go with it. same i installed on ongoing project.
Version Magento CE 1.9.1.1

If all extensions work on clean and unmodified version then i am sooryyyyy....and i never saw any unmodified magento website on the web.

**Comment by husseycoding** [comment]
The purpose of asking if you are using it on a clean unmodified install of Magento is to determine if the issue is apparent in the extension or introduced by modifications to your install.  If you want us to look at the issue anyway without first running this test then feel free to contact us at support@husseycoding.co.uk for paid support services.

**Comment by farazWebDev** [comment]
Thanks Man for valued supported. Thanks and Sorry if i hurt you.

**Comment by husseycoding** [comment]
Insufficient information to determine if there is a bug with the actual extension so appears to be invalid but will test anyway for next release to confirm whether work is needed here or not.
